services:
  postgres:
    image: postgres:16

    container_name: docuflow-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: docuflow_db
      POSTGRES_USER: docuflow_user
      POSTGRES_PASSWORD: docuflow_password

    ports:
      # Local computer port 5434 connects to
      # PostgreSQL's internal port 5432.
      - "5434:5432"

    volumes:
      # Preserve database data when the container stops.
      - docuflow-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U docuflow_user -d docuflow_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  docuflow-postgres-data: