"""add ai analysis fields to documents

Revision ID: 26fdc353d05e
Revises: 2dbb6e385111
Create Date: 2026-09-16 17:19:51.535496

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26fdc353d05e"
down_revision: str | Sequence[str] | None = "2dbb6e385111"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("classification_confidence", sa.Float(), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column(
            "extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "extracted_data")
    op.drop_column("documents", "classification_confidence")
    # ### end Alembic commands ###
